env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    gh_token: "ENCRYPTED[cfdc7ba2621157720b2b5ed2553d996d7e6b1b652030f94ccecc8d0b638cc96416ba103920e9eb34f30904a01682fbf4]"
    bot_api: "ENCRYPTED[21b145c753e8c20087278af7bd9279d918c1fb2b34867849c67c5bc117a12ec2039ddcd7a793698488492662d7fcdbcb]"
    chat_id: "ENCRYPTED[1268a868d7290ee3ecd8350f35d4fe12fb60e9a63330d2d105a26e507b9479919052cac11930475b6695716370c6632b]"
    rom: "ssos"
  
task:
    name: aosp
    timeout_in: 260m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    download_ccache_background_script: # To download ccache in background
      - bash download_ccache # Ccache download script
    sync_script:
      - bash sync
    build_script:
      - bash build full gh
    upload_ccache_script: # Upload ccache to cloud foreground
      - bash upload_ccache gh # Ccache uploading script
