#!/bin/bash

cd /tmp/ccache_backup

echo "|| Compressing CCACHE ||"
7za a -tzip -v25m ccache_backup.zip /tmp/ccache/* -sdel

echo "|| Uploading CCACHE ||"
git add .
git commit -sm "CCACHE: IMPORT CCACHE FROM NEW BUILD"
git push -f

# clean storage
rm -rf /tmp/*
